# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hyprbazz
# description will be included in the image's metadata
description: This is my personal OS image made for gaming and coding on hyprland.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/hyprland
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        #- atim/starship
        - azandure/clipse
        - tofik/nwg-shell
        #- yanqiyu/waydroid
        # - guillermodotn/cliphist #repo is outdated

      files:
        - vscodium.repo
        - https://download.docker.com/linux/fedora/docker-ce.repo

      nonfree: negativo17 #dont go rpm-fusion it kills everything
      cleanup: true

    install:
      packages:
        # utils
        - qt6ct
        - foot
        # files
        - dolphin
        - hyprland-devel
        - neovim
        - syncthing
        - onedrive
        - filelight
        #- starship
        - distrobox
        #- waydroid
        #- xfce4-settings
        ## nwg-shell
        #- nwg-shell
        #- nwg-shell-config
        #- nwg-clipman
        - nwg-displays
        - nwg-look
        #- nwg-dock
        #- nwg-drawer
        #- nwg-icon-picker
        #- nwg-menu

        - steam
        - gamescope
        - mangohud

        ## dev stuff
        - podman-compose
        - codium
        ### docker
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

        # winboat
        - freerdp
        - https://github.com/TibixDev/winboat/releases/download/v0.9.0/winboat-0.9.0-x86_64.rpm
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        - kitty
        - firefox # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox-langpacks

        - Thunar # switch to nemo
        #- xarchiver # switch to nemo

  - type: default-flatpaks
    configurations:
      - scope: user
        repo:
          # you can override the title to make inclusion of both system and user repos clearer
          title: Flathub (user)
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        repo:
          title: Flathub (system)
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - io.gitlab.librewolf-community
          - org.signal.Signal
          - org.onlyoffice.desktopeditors
          - io.github.kolunmi.Bazaar

  #- type: brew
  #  nofile-limits: true # increase nofile limits

  - type: script
    snippets:
      - curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64" && install -c -m 0755 devpod /usr/local/bin && rm -f devpod
      #- wget -qO- https://apx.vanillaos.org/install.sh | bash
      - chmod a+x /bin/update
      - chmod a+x /bin/hyprltm-net
      - systemctl --global enable ssh-agent
      - systemctl enable --now docker
      #- curl -s https://api.github.com/repos/TibixDev/winboat/releases/latest | grep browser_download_url | grep AppImage | cut -d '"' -f 4 | wget -P /usr/bin && chomd a+x /usr/bin/winboat**
    scripts:
      - get_clipvault.sh

  # - hyprpm add https://github.com/KZDKM/Hyprspace && hyprpm enable Hyprspace
  # hyprspce (Workspaces)
  #- hyprpm add https://github.com/KZDKM/Hyprspace && hyprpm enable Hyprspace

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
