# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hyprbazz
# description will be included in the image's metadata
description: This is my personal OS image made for gaming on hyprland.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/hyprland
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - tofik/nwg-shell
      nonfree: negativo17

    install:
      packages:
        # utils
        - qt6ct
        - foot
        - neovim
        - syncthing
        - onedrive
        - filelight
        - starship
        ## nwg-shell
        - nwg-shell
        - nwg-shell-config
        - nwg-clipman
        - nwg-displays
        - nwg-dock
        - nwg-drawer
        - nwg-icon-picker
        - nwg-look
        - nwg-menu

        - steam
        - gamescope
        - mangohud

        ## dev stuff
        - podman-compose
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        - kitty
        - firefox # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - io.gitlab.librewolf-community
          - org.signal.Signal
          - org.onlyoffice.desktopeditors
          - io.github.kolunmi.Bazaar

      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  - type: brew
    nofile-limits: true # increase nofile limits
